package de.jawb.tools.iso;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.apache.commons.lang.LocaleUtils;

import de.jawb.tools.iso.i18n.ITranslatable;

/**
 * CountryList ISO 3166<br>
 * 
 * @author dit (24.11.2012)
 */
public enum Country2 implements ITranslatable {
    
    Afghanistan(
            "Afghanistan",
            "af",
            "afg",
            new String[] {},
            "Kabul",
            "93",
            Currency.Afghanistan_Afghani,
            Continent.Asia),
    Aland_Islands(
            "Aland Islands",
            "ax",
            "ala",
            new String[] {},
            "Mariehamn",
            "+358-18",
            Currency.Euro,
            Continent.Europe),
    Albania(
            "Albania",
            "al",
            "alb",
            new String[] { "sq" },
            "Tirana",
            "355",
            Currency.Albanian_Lek,
            Continent.Europe),
    Algeria(
            "Algeria",
            "dz",
            "dza",
            new String[] { "ar" },
            "Algiers",
            "213",
            Currency.Algerian_Dinar,
            Continent.Africa),
    American_Samoa(
            "American Samoa",
            "as",
            "asm",
            new String[] {},
            "Pago Pago",
            "+1-684",
            Currency.US_Dollar,
            Continent.Oceania),
    Andorra(
            "Andorra",
            "ad",
            "and",
            new String[] {},
            "Andorra la Vella",
            "376",
            Currency.Euro,
            Continent.Europe),
    Angola(
            "Angola",
            "ao",
            "ago",
            new String[] {},
            "Luanda",
            "244",
            Currency.Angolan_Kwanza,
            Continent.Africa),
    Anguilla(
            "Anguilla",
            "ai",
            "aia",
            new String[] {},
            "The Valley",
            "+1-264",
            Currency.East_Caribbean_Dollar,
            Continent.North_America),
    Antigua_and_Barbuda(
            "Antigua and Barbuda",
            "ag",
            "atg",
            new String[] {},
            "St. John's",
            "+1-268",
            Currency.East_Caribbean_Dollar,
            Continent.North_America),
    Argentina(
            "Argentina",
            "ar",
            "arg",
            new String[] { "es" },
            "Buenos Aires",
            "54",
            Currency.Argentine_Peso,
            Continent.South_America),
    Armenia(
            "Armenia",
            "am",
            "arm",
            new String[] {},
            "Yerevan",
            "374",
            Currency.Armenian_Dram,
            Continent.Asia),
    Aruba(
            "Aruba",
            "aw",
            "abw",
            new String[] {},
            "Oranjestad",
            "297",
            Currency.Aruban_Guilder,
            Continent.North_America),
    Australia(
            "Australia",
            "au",
            "aus",
            new String[] { "en" },
            "Canberra",
            "61",
            Currency.Australian_Dollar,
            Continent.Oceania),
    Austria(
            "Austria",
            "at",
            "aut",
            new String[] { "de" },
            "Vienna",
            "43",
            Currency.Euro,
            Continent.Europe),
    Azerbaijan(
            "Azerbaijan",
            "az",
            "aze",
            new String[] {},
            "Baku",
            "994",
            Currency.Azerbaijan_New_Manat,
            Continent.Asia),
    Bahamas(
            "Bahamas",
            "bs",
            "bhs",
            new String[] {},
            "Nassau",
            "+1-242",
            Currency.Bahamian_Dollar,
            Continent.North_America),
    Bahrain(
            "Bahrain",
            "bh",
            "bhr",
            new String[] { "ar" },
            "Manama",
            "973",
            Currency.Bahraini_Dinar,
            Continent.Asia),
    Bangladesh(
            "Bangladesh",
            "bd",
            "bgd",
            new String[] {},
            "Dhaka",
            "880",
            Currency.Bangladeshi_Taka,
            Continent.Asia),
    Barbados(
            "Barbados",
            "bb",
            "brb",
            new String[] {},
            "Bridgetown",
            "+1-246",
            Currency.Barbados_Dollar,
            Continent.North_America),
    Belarus(
            "Belarus",
            "by",
            "blr",
            new String[] { "be" },
            "Minsk",
            "375",
            Currency.Belarussian_Ruble,
            Continent.Europe),
    Belgium(
            "Belgium",
            "be",
            "bel",
            new String[] { "fr", "nl" },
            "Brussels",
            "32",
            Currency.Euro,
            Continent.Europe),
    Belize(
            "Belize",
            "bz",
            "blz",
            new String[] {},
            "Belmopan",
            "501",
            Currency.Belize_Dollar,
            Continent.North_America),
    Benin(
            "Benin",
            "bj",
            "ben",
            new String[] {},
            "Porto-Novo",
            "229",
            Currency.CFA_Franc_BCEAO,
            Continent.Africa),
    Bermuda(
            "Bermuda",
            "bm",
            "bmu",
            new String[] {},
            "Hamilton",
            "+1-441",
            Currency.Bermudian_Dollar,
            Continent.North_America),
    Bhutan(
            "Bhutan",
            "bt",
            "btn",
            new String[] {},
            "Thimphu",
            "975",
            Currency.Bhutan_Ngultrum,
            Continent.Asia),
    Bolivia(
            "Bolivia",
            "bo",
            "bol",
            new String[] { "es" },
            "Sucre",
            "591",
            Currency.Boliviano,
            Continent.South_America),
    Bonaire(
            "Bonaire",
            "bq",
            "bes",
            new String[] {},
            "",
            "599",
            Currency.US_Dollar,
            Continent.North_America),
    Bosnia_and_Herzegovina(
            "Bosnia and Herzegovina",
            "ba",
            "bih",
            new String[] { "sr", "sr" },
            "Sarajevo",
            "387",
            Currency.Marka,
            Continent.Europe),
    Botswana(
            "Botswana",
            "bw",
            "bwa",
            new String[] {},
            "Gaborone",
            "267",
            Currency.Botswana_Pula,
            Continent.Africa),
    Bouvet_Island(
            "Bouvet Island",
            "bv",
            "bvt",
            new String[] {},
            "",
            "",
            Currency.Norwegian_Krone,
            Continent.Antarctica),
    Brazil(
            "Brazil",
            "br",
            "bra",
            new String[] { "pt" },
            "Brasilia",
            "55",
            Currency.Brazilian_Real,
            Continent.South_America),
    British_Indian_Ocean_Territory(
            "British Indian Ocean Territory",
            "io",
            "iot",
            new String[] {},
            "Diego Garcia",
            "246",
            Currency.US_Dollar,
            Continent.Asia),
    British_Virgin_Islands(
            "British Virgin Islands",
            "vg",
            "vgb",
            new String[] {},
            "Road Town",
            "+1-284",
            Currency.US_Dollar,
            Continent.North_America),
    Brunei(
            "Brunei",
            "bn",
            "brn",
            new String[] {},
            "Bandar Seri Begawan",
            "673",
            Currency.Brunei_Dollar,
            Continent.Asia),
    Bulgaria(
            "Bulgaria",
            "bg",
            "bgr",
            new String[] { "bg" },
            "Sofia",
            "359",
            Currency.Bulgarian_Lev,
            Continent.Europe),
    Burkina_Faso(
            "Burkina Faso",
            "bf",
            "bfa",
            new String[] {},
            "Ouagadougou",
            "226",
            Currency.CFA_Franc_BCEAO,
            Continent.Africa),
    Burundi(
            "Burundi",
            "bi",
            "bdi",
            new String[] {},
            "Bujumbura",
            "257",
            Currency.Burundi_Franc,
            Continent.Africa),
    Cambodia(
            "Cambodia",
            "kh",
            "khm",
            new String[] {},
            "Phnom Penh",
            "855",
            Currency.Kampuchean_Riel,
            Continent.Asia),
    Cameroon(
            "Cameroon",
            "cm",
            "cmr",
            new String[] {},
            "Yaounde",
            "237",
            Currency.CFA_Franc_BEAC,
            Continent.Africa),
    Canada(
            "Canada",
            "ca",
            "can",
            new String[] { "fr", "en" },
            "Ottawa",
            "1",
            Currency.Canadian_Dollar,
            Continent.North_America),
    Cape_Verde(
            "Cape Verde",
            "cv",
            "cpv",
            new String[] {},
            "Praia",
            "238",
            Currency.Cape_Verde_Escudo,
            Continent.Africa),
    Cayman_Islands(
            "Cayman Islands",
            "ky",
            "cym",
            new String[] {},
            "George Town",
            "+1-345",
            Currency.Cayman_Islands_Dollar,
            Continent.North_America),
    Central_African_Republic(
            "Central African Republic",
            "cf",
            "caf",
            new String[] {},
            "Bangui",
            "236",
            Currency.CFA_Franc_BEAC,
            Continent.Africa),
    Chad(
            "Chad",
            "td",
            "tcd",
            new String[] {},
            "N'Djamena",
            "235",
            Currency.CFA_Franc_BEAC,
            Continent.Africa),
    Chile(
            "Chile",
            "cl",
            "chl",
            new String[] { "es" },
            "Santiago",
            "56",
            Currency.Chilean_Peso,
            Continent.South_America),
    China(
            "China",
            "cn",
            "chn",
            new String[] { "zh" },
            "Beijing",
            "86",
            Currency.Yuan_Renminbi,
            Continent.Asia),
    Christmas_Island(
            "Christmas Island",
            "cx",
            "cxr",
            new String[] {},
            "Flying Fish Cove",
            "61",
            Currency.Australian_Dollar,
            Continent.Asia),
    Cocos_Islands(
            "Cocos Islands",
            "cc",
            "cck",
            new String[] {},
            "West Island",
            "61",
            Currency.Australian_Dollar,
            Continent.Asia),
    Colombia(
            "Colombia",
            "co",
            "col",
            new String[] { "es" },
            "Bogota",
            "57",
            Currency.Colombian_Peso,
            Continent.South_America),
    Comoros(
            "Comoros",
            "km",
            "com",
            new String[] {},
            "Moroni",
            "269",
            Currency.Comoros_Franc,
            Continent.Africa),
    Cook_Islands(
            "Cook Islands",
            "ck",
            "cok",
            new String[] {},
            "Avarua",
            "682",
            Currency.New_Zealand_Dollar,
            Continent.Oceania),
    Costa_Rica(
            "Costa Rica",
            "cr",
            "cri",
            new String[] { "es" },
            "San Jose",
            "506",
            Currency.Costa_Rican_Colon,
            Continent.North_America),
    Croatia(
            "Croatia",
            "hr",
            "hrv",
            new String[] { "hr" },
            "Zagreb",
            "385",
            Currency.Croatian_Kuna,
            Continent.Europe),
    Cuba(
            "Cuba",
            "cu",
            "cub",
            new String[] { "es" },
            "Havana",
            "53",
            Currency.Cuban_Peso,
            Continent.North_America),
    Curacao(
            "Curacao",
            "cw",
            "cuw",
            new String[] {},
            "Willemstad",
            "599",
            Currency.Netherlands_Antillean_Guilder,
            Continent.North_America),
    Cyprus(
            "Cyprus",
            "cy",
            "cyp",
            new String[] { "el" },
            "Nicosia",
            "357",
            Currency.Euro,
            Continent.Europe),
    Czech_Republic(
            "Czech Republic",
            "cz",
            "cze",
            new String[] { "cs" },
            "Prague",
            "420",
            Currency.Czech_Koruna,
            Continent.Europe),
    Democratic_Republic_of_the_Congo(
            "Democratic Republic of the Congo",
            "cd",
            "cod",
            new String[] {},
            "Kinshasa",
            "243",
            Currency.Francs,
            Continent.Africa),
    Denmark(
            "Denmark",
            "dk",
            "dnk",
            new String[] { "da" },
            "Copenhagen",
            "45",
            Currency.Danish_Krone,
            Continent.Europe),
    Djibouti(
            "Djibouti",
            "dj",
            "dji",
            new String[] {},
            "Djibouti",
            "253",
            Currency.Djibouti_Franc,
            Continent.Africa),
    Dominica(
            "Dominica",
            "dm",
            "dma",
            new String[] {},
            "Roseau",
            "+1-767",
            Currency.East_Caribbean_Dollar,
            Continent.North_America),
    Dominican_Republic(
            "Dominican Republic",
            "do",
            "dom",
            new String[] { "es" },
            "Santo Domingo",
            "+1-809 and 1-829",
            Currency.Dominican_Peso,
            Continent.North_America),
    East_Timor(
            "East Timor",
            "tl",
            "tls",
            new String[] {},
            "Dili",
            "670",
            Currency.US_Dollar,
            Continent.Oceania),
    Ecuador(
            "Ecuador",
            "ec",
            "ecu",
            new String[] { "es" },
            "Quito",
            "593",
            Currency.US_Dollar,
            Continent.South_America),
    Egypt(
            "Egypt",
            "eg",
            "egy",
            new String[] { "ar" },
            "Cairo",
            "20",
            Currency.Egyptian_Pound,
            Continent.Africa),
    El_Salvador(
            "El Salvador",
            "sv",
            "slv",
            new String[] { "es" },
            "San Salvador",
            "503",
            Currency.US_Dollar,
            Continent.North_America),
    Equatorial_Guinea(
            "Equatorial Guinea",
            "gq",
            "gnq",
            new String[] {},
            "Malabo",
            "240",
            Currency.CFA_Franc_BEAC,
            Continent.Africa),
    Eritrea(
            "Eritrea",
            "er",
            "eri",
            new String[] {},
            "Asmara",
            "291",
            Currency.Eritrean_Nakfa,
            Continent.Africa),
    Estonia(
            "Estonia",
            "ee",
            "est",
            new String[] { "et" },
            "Tallinn",
            "372",
            Currency.Euro,
            Continent.Europe),
    Ethiopia(
            "Ethiopia",
            "et",
            "eth",
            new String[] {},
            "Addis Ababa",
            "251",
            Currency.Ethiopian_Birr,
            Continent.Africa),
    Falkland_Islands(
            "Falkland Islands",
            "fk",
            "flk",
            new String[] {},
            "Stanley",
            "500",
            Currency.Falkland_Islands_Pound,
            Continent.South_America),
    Faroe_Islands(
            "Faroe Islands",
            "fo",
            "fro",
            new String[] {},
            "Torshavn",
            "298",
            Currency.Danish_Krone,
            Continent.Europe),
    Fiji(
            "Fiji",
            "fj",
            "fji",
            new String[] {},
            "Suva",
            "679",
            Currency.Fiji_Dollar,
            Continent.Oceania),
    Finland(
            "Finland",
            "fi",
            "fin",
            new String[] { "fi" },
            "Helsinki",
            "358",
            Currency.Euro,
            Continent.Europe),
    France(
            "France",
            "fr",
            "fra",
            new String[] { "fr" },
            "Paris",
            "33",
            Currency.Euro,
            Continent.Europe),
    French_Guiana(
            "French Guiana",
            "gf",
            "guf",
            new String[] {},
            "Cayenne",
            "594",
            Currency.Euro,
            Continent.South_America),
    French_Polynesia(
            "French Polynesia",
            "pf",
            "pyf",
            new String[] {},
            "Papeete",
            "689",
            Currency.CFP_Franc,
            Continent.Oceania),
    French_Southern_Territories(
            "French Southern Territories",
            "tf",
            "atf",
            new String[] {},
            "Port-aux-Francais",
            "",
            Currency.Euro,
            Continent.Antarctica),
    Gabon(
            "Gabon",
            "ga",
            "gab",
            new String[] {},
            "Libreville",
            "241",
            Currency.CFA_Franc_BEAC,
            Continent.Africa),
    Gambia(
            "Gambia",
            "gm",
            "gmb",
            new String[] {},
            "Banjul",
            "220",
            Currency.Gambian_Dalasi,
            Continent.Africa),
    Georgia(
            "Georgia",
            "ge",
            "geo",
            new String[] {},
            "Tbilisi",
            "995",
            Currency.Georgian_Lari,
            Continent.Asia),
    Germany(
            "Germany",
            "de",
            "deu",
            new String[] { "de" },
            "Berlin",
            "49",
            Currency.Euro,
            Continent.Europe),
    Ghana(
            "Ghana",
            "gh",
            "gha",
            new String[] {},
            "Accra",
            "233",
            Currency.Ghanaian_Cedi,
            Continent.Africa),
    Gibraltar(
            "Gibraltar",
            "gi",
            "gib",
            new String[] {},
            "Gibraltar",
            "350",
            Currency.Gibraltar_Pound,
            Continent.Europe),
    Greece(
            "Greece",
            "gr",
            "grc",
            new String[] { "el", "de" },
            "Athens",
            "30",
            Currency.Euro,
            Continent.Europe),
    Greenland(
            "Greenland",
            "gl",
            "grl",
            new String[] {},
            "Nuuk",
            "299",
            Currency.Danish_Krone,
            Continent.North_America),
    Grenada(
            "Grenada",
            "gd",
            "grd",
            new String[] {},
            "St. George's",
            "+1-473",
            Currency.East_Caribbean_Dollar,
            Continent.North_America),
    Guadeloupe(
            "Guadeloupe",
            "gp",
            "glp",
            new String[] {},
            "Basse-Terre",
            "590",
            Currency.Euro,
            Continent.North_America),
    Guam(
            "Guam",
            "gu",
            "gum",
            new String[] {},
            "Hagatna",
            "+1-671",
            Currency.US_Dollar,
            Continent.Oceania),
    Guatemala(
            "Guatemala",
            "gt",
            "gtm",
            new String[] { "es" },
            "Guatemala City",
            "502",
            Currency.Guatemalan_Quetzal,
            Continent.North_America),
    Guernsey(
            "Guernsey",
            "gg",
            "ggy",
            new String[] {},
            "St Peter Port",
            "+44-1481",
            Currency.Pound_Sterling,
            Continent.Europe),
    Guinea(
            "Guinea",
            "gn",
            "gin",
            new String[] {},
            "Conakry",
            "224",
            Currency.Guinea_Franc,
            Continent.Africa),
    GuineaBissau(
            "Guinea-Bissau",
            "gw",
            "gnb",
            new String[] {},
            "Bissau",
            "245",
            Currency.CFA_Franc_BCEAO,
            Continent.Africa),
    Guyana(
            "Guyana",
            "gy",
            "guy",
            new String[] {},
            "Georgetown",
            "592",
            Currency.Guyana_Dollar,
            Continent.South_America),
    Haiti(
            "Haiti",
            "ht",
            "hti",
            new String[] {},
            "Port-au-Prince",
            "509",
            Currency.Haitian_Gourde,
            Continent.North_America),
    Heard_Island_and_McDonald_Islands(
            "Heard Island and McDonald Islands",
            "hm",
            "hmd",
            new String[] {},
            "",
            "",
            Currency.Australian_Dollar,
            Continent.Antarctica),
    Honduras(
            "Honduras",
            "hn",
            "hnd",
            new String[] { "es" },
            "Tegucigalpa",
            "504",
            Currency.Honduran_Lempira,
            Continent.North_America),
    Hong_Kong(
            "Hong Kong",
            "hk",
            "hkg",
            new String[] { "zh" },
            "Hong Kong",
            "852",
            Currency.Hong_Kong_Dollar,
            Continent.Asia),
    Hungary(
            "Hungary",
            "hu",
            "hun",
            new String[] { "hu" },
            "Budapest",
            "36",
            Currency.Hungarian_Forint,
            Continent.Europe),
    Iceland(
            "Iceland",
            "is",
            "isl",
            new String[] { "is" },
            "Reykjavik",
            "354",
            Currency.Iceland_Krona,
            Continent.Europe),
    India(
            "India",
            "in",
            "ind",
            new String[] { "hi", "en" },
            "New Delhi",
            "91",
            Currency.Indian_Rupee,
            Continent.Asia),
    Indonesia(
            "Indonesia",
            "id",
            "idn",
            new String[] { "in" },
            "Jakarta",
            "62",
            Currency.Indonesian_Rupiah,
            Continent.Asia),
    Iran(
            "Iran",
            "ir",
            "irn",
            new String[] {},
            "Tehran",
            "98",
            Currency.Iranian_Rial,
            Continent.Asia),
    Iraq(
            "Iraq",
            "iq",
            "irq",
            new String[] { "ar" },
            "Baghdad",
            "964",
            Currency.Iraqi_Dinar,
            Continent.Asia),
    Ireland(
            "Ireland",
            "ie",
            "irl",
            new String[] { "ga", "en" },
            "Dublin",
            "353",
            Currency.Euro,
            Continent.Europe),
    Isle_of_Man(
            "Isle of Man",
            "im",
            "imn",
            new String[] {},
            "Douglas, Isle of Man",
            "+44-1624",
            Currency.Pound_Sterling,
            Continent.Europe),
    Israel(
            "Israel",
            "il",
            "isr",
            new String[] { "iw" },
            "Jerusalem",
            "972",
            Currency.Israeli_New_Shekel,
            Continent.Asia),
    Italy(
            "Italy",
            "it",
            "ita",
            new String[] { "it" },
            "Rome",
            "39",
            Currency.Euro,
            Continent.Europe),
    Ivory_Coast(
            "Ivory Coast",
            "ci",
            "civ",
            new String[] {},
            "Yamoussoukro",
            "225",
            Currency.CFA_Franc_BCEAO,
            Continent.Africa),
    Jamaica(
            "Jamaica",
            "jm",
            "jam",
            new String[] {},
            "Kingston",
            "+1-876",
            Currency.Jamaican_Dollar,
            Continent.North_America),
    Japan(
            "Japan",
            "jp",
            "jpn",
            new String[] { "ja" },
            "Tokyo",
            "81",
            Currency.Japanese_Yen,
            Continent.Asia),
    Jersey(
            "Jersey",
            "je",
            "jey",
            new String[] {},
            "Saint Helier",
            "+44-1534",
            Currency.Pound_Sterling,
            Continent.Europe),
    Jordan(
            "Jordan",
            "jo",
            "jor",
            new String[] { "ar" },
            "Amman",
            "962",
            Currency.Jordanian_Dinar,
            Continent.Asia),
    Kazakhstan(
            "Kazakhstan",
            "kz",
            "kaz",
            new String[] {},
            "Astana",
            "7",
            Currency.Kazakhstan_Tenge,
            Continent.Asia),
    Kenya(
            "Kenya",
            "ke",
            "ken",
            new String[] {},
            "Nairobi",
            "254",
            Currency.Kenyan_Shilling,
            Continent.Africa),
    Kiribati(
            "Kiribati",
            "ki",
            "kir",
            new String[] {},
            "Tarawa",
            "686",
            Currency.Australian_Dollar,
            Continent.Oceania),
    Kosovo(
            "Kosovo",
            "xk",
            "xkx",
            new String[] {},
            "Pristina",
            "",
            Currency.Euro,
            Continent.Europe),
    Kuwait(
            "Kuwait",
            "kw",
            "kwt",
            new String[] { "ar" },
            "Kuwait City",
            "965",
            Currency.Kuwaiti_Dinar,
            Continent.Asia),
    Kyrgyzstan(
            "Kyrgyzstan",
            "kg",
            "kgz",
            new String[] {},
            "Bishkek",
            "996",
            Currency.Som,
            Continent.Asia),
    Laos(
            "Laos",
            "la",
            "lao",
            new String[] {},
            "Vientiane",
            "856",
            Currency.Lao_Kip,
            Continent.Asia),
    Latvia(
            "Latvia",
            "lv",
            "lva",
            new String[] { "lv" },
            "Riga",
            "371",
            Currency.Euro,
            Continent.Europe),
    Lebanon(
            "Lebanon",
            "lb",
            "lbn",
            new String[] { "ar" },
            "Beirut",
            "961",
            Currency.Lebanese_Pound,
            Continent.Asia),
    Lesotho(
            "Lesotho",
            "ls",
            "lso",
            new String[] {},
            "Maseru",
            "266",
            Currency.Lesotho_Loti,
            Continent.Africa),
    Liberia(
            "Liberia",
            "lr",
            "lbr",
            new String[] {},
            "Monrovia",
            "231",
            Currency.Liberian_Dollar,
            Continent.Africa),
    Libya(
            "Libya",
            "ly",
            "lby",
            new String[] { "ar" },
            "Tripolis",
            "218",
            Currency.Libyan_Dinar,
            Continent.Africa),
    Liechtenstein(
            "Liechtenstein",
            "li",
            "lie",
            new String[] {},
            "Vaduz",
            "423",
            Currency.Swiss_Franc,
            Continent.Europe),
    Lithuania(
            "Lithuania",
            "lt",
            "ltu",
            new String[] { "lt" },
            "Vilnius",
            "370",
            Currency.Lithuanian_Litas,
            Continent.Europe),
    Luxembourg(
            "Luxembourg",
            "lu",
            "lux",
            new String[] { "fr", "de" },
            "Luxembourg",
            "352",
            Currency.Euro,
            Continent.Europe),
    Macao(
            "Macao",
            "mo",
            "mac",
            new String[] {},
            "Macao",
            "853",
            Currency.Macau_Pataca,
            Continent.Asia),
    Macedonia(
            "Macedonia",
            "mk",
            "mkd",
            new String[] { "mk" },
            "Skopje",
            "389",
            Currency.Denar,
            Continent.Europe),
    Madagascar(
            "Madagascar",
            "mg",
            "mdg",
            new String[] {},
            "Antananarivo",
            "261",
            Currency.Malagasy_Ariary,
            Continent.Africa),
    Malawi(
            "Malawi",
            "mw",
            "mwi",
            new String[] {},
            "Lilongwe",
            "265",
            Currency.Malawi_Kwacha,
            Continent.Africa),
    Malaysia(
            "Malaysia",
            "my",
            "mys",
            new String[] { "ms" },
            "Kuala Lumpur",
            "60",
            Currency.Malaysian_Ringgit,
            Continent.Asia),
    Maldives(
            "Maldives",
            "mv",
            "mdv",
            new String[] {},
            "Male",
            "960",
            Currency.Maldive_Rufiyaa,
            Continent.Asia),
    Mali(
            "Mali",
            "ml",
            "mli",
            new String[] {},
            "Bamako",
            "223",
            Currency.CFA_Franc_BCEAO,
            Continent.Africa),
    Malta(
            "Malta",
            "mt",
            "mlt",
            new String[] { "mt", "en" },
            "Valletta",
            "356",
            Currency.Euro,
            Continent.Europe),
    Marshall_Islands(
            "Marshall Islands",
            "mh",
            "mhl",
            new String[] {},
            "Majuro",
            "692",
            Currency.US_Dollar,
            Continent.Oceania),
    Martinique(
            "Martinique",
            "mq",
            "mtq",
            new String[] {},
            "Fort-de-France",
            "596",
            Currency.Euro,
            Continent.North_America),
    Mauritania(
            "Mauritania",
            "mr",
            "mrt",
            new String[] {},
            "Nouakchott",
            "222",
            Currency.Mauritanian_Ouguiya,
            Continent.Africa),
    Mauritius(
            "Mauritius",
            "mu",
            "mus",
            new String[] {},
            "Port Louis",
            "230",
            Currency.Mauritius_Rupee,
            Continent.Africa),
    Mayotte(
            "Mayotte",
            "yt",
            "myt",
            new String[] {},
            "Mamoudzou",
            "262",
            Currency.Euro,
            Continent.Africa),
    Mexico(
            "Mexico",
            "mx",
            "mex",
            new String[] { "es" },
            "Mexico City",
            "52",
            Currency.Mexican_Nuevo_Peso,
            Continent.North_America),
    Micronesia(
            "Micronesia",
            "fm",
            "fsm",
            new String[] {},
            "Palikir",
            "691",
            Currency.US_Dollar,
            Continent.Oceania),
    Moldova(
            "Moldova",
            "md",
            "mda",
            new String[] {},
            "Chisinau",
            "373",
            Currency.Moldovan_Leu,
            Continent.Europe),
    Monaco(
            "Monaco",
            "mc",
            "mco",
            new String[] {},
            "Monaco",
            "377",
            Currency.Euro,
            Continent.Europe),
    Mongolia(
            "Mongolia",
            "mn",
            "mng",
            new String[] {},
            "Ulan Bator",
            "976",
            Currency.Mongolian_Tugrik,
            Continent.Asia),
    Montenegro(
            "Montenegro",
            "me",
            "mne",
            new String[] { "sr", "sr" },
            "Podgorica",
            "382",
            Currency.Euro,
            Continent.Europe),
    Montserrat(
            "Montserrat",
            "ms",
            "msr",
            new String[] {},
            "Plymouth",
            "+1-664",
            Currency.East_Caribbean_Dollar,
            Continent.North_America),
    Morocco(
            "Morocco",
            "ma",
            "mar",
            new String[] { "ar" },
            "Rabat",
            "212",
            Currency.Moroccan_Dirham,
            Continent.Africa),
    Mozambique(
            "Mozambique",
            "mz",
            "moz",
            new String[] {},
            "Maput",
            "258",
            Currency.Mozambique_Metical,
            Continent.Africa),
    Myanmar(
            "Myanmar",
            "mm",
            "mmr",
            new String[] {},
            "Nay Pyi Taw",
            "95",
            Currency.Myanmar_Kyat,
            Continent.Asia),
    Namibia(
            "Namibia",
            "na",
            "nam",
            new String[] {},
            "Windhoek",
            "264",
            Currency.Namibian_Dollar,
            Continent.Africa),
    Nauru(
            "Nauru",
            "nr",
            "nru",
            new String[] {},
            "Yaren",
            "674",
            Currency.Australian_Dollar,
            Continent.Oceania),
    Nepal(
            "Nepal",
            "np",
            "npl",
            new String[] {},
            "Kathmandu",
            "977",
            Currency.Nepalese_Rupee,
            Continent.Asia),
    Netherlands(
            "Netherlands",
            "nl",
            "nld",
            new String[] { "nl" },
            "Amsterdam",
            "31",
            Currency.Euro,
            Continent.Europe),
    New_Caledonia(
            "New Caledonia",
            "nc",
            "ncl",
            new String[] {},
            "Noumea",
            "687",
            Currency.CFP_Franc,
            Continent.Oceania),
    New_Zealand(
            "New Zealand",
            "nz",
            "nzl",
            new String[] { "en" },
            "Wellington",
            "64",
            Currency.New_Zealand_Dollar,
            Continent.Oceania),
    Nicaragua(
            "Nicaragua",
            "ni",
            "nic",
            new String[] { "es" },
            "Managua",
            "505",
            Currency.Nicaraguan_Cordoba_Oro,
            Continent.North_America),
    Niger(
            "Niger",
            "ne",
            "ner",
            new String[] {},
            "Niamey",
            "227",
            Currency.CFA_Franc_BCEAO,
            Continent.Africa),
    Nigeria(
            "Nigeria",
            "ng",
            "nga",
            new String[] {},
            "Abuja",
            "234",
            Currency.Nigerian_Naira,
            Continent.Africa),
    Niue(
            "Niue",
            "nu",
            "niu",
            new String[] {},
            "Alofi",
            "683",
            Currency.New_Zealand_Dollar,
            Continent.Oceania),
    Norfolk_Island(
            "Norfolk Island",
            "nf",
            "nfk",
            new String[] {},
            "Kingston",
            "672",
            Currency.Australian_Dollar,
            Continent.Oceania),
    North_Korea(
            "North Korea",
            "kp",
            "prk",
            new String[] {},
            "Pyongyang",
            "850",
            Currency.North_Korean_Won,
            Continent.Asia),
    Northern_Mariana_Islands(
            "Northern Mariana Islands",
            "mp",
            "mnp",
            new String[] {},
            "Saipan",
            "+1-670",
            Currency.US_Dollar,
            Continent.Oceania),
    Norway(
            "Norway",
            "no",
            "nor",
            new String[] { "no" },
            "Oslo",
            "47",
            Currency.Norwegian_Krone,
            Continent.Europe),
    Oman(
            "Oman",
            "om",
            "omn",
            new String[] { "ar" },
            "Muscat",
            "968",
            Currency.Omani_Rial,
            Continent.Asia),
    Pakistan(
            "Pakistan",
            "pk",
            "pak",
            new String[] {},
            "Islamabad",
            "92",
            Currency.Pakistan_Rupee,
            Continent.Asia),
    Palau(
            "Palau",
            "pw",
            "plw",
            new String[] {},
            "Melekeok",
            "680",
            Currency.US_Dollar,
            Continent.Oceania),
    Palestinian_Territory(
            "Palestinian Territory",
            "ps",
            "pse",
            new String[] {},
            "East Jerusalem",
            "970",
            Currency.Israeli_New_Shekel,
            Continent.Asia),
    Panama(
            "Panama",
            "pa",
            "pan",
            new String[] { "es" },
            "Panama City",
            "507",
            Currency.Panamanian_Balboa,
            Continent.North_America),
    Papua_New_Guinea(
            "Papua New Guinea",
            "pg",
            "png",
            new String[] {},
            "Port Moresby",
            "675",
            Currency.Papua_New_Guinea_Kina,
            Continent.Oceania),
    Paraguay(
            "Paraguay",
            "py",
            "pry",
            new String[] { "es" },
            "Asuncion",
            "595",
            Currency.Paraguay_Guarani,
            Continent.South_America),
    Peru(
            "Peru",
            "pe",
            "per",
            new String[] { "es" },
            "Lima",
            "51",
            Currency.Peruvian_Nuevo_Sol,
            Continent.South_America),
    Philippines(
            "Philippines",
            "ph",
            "phl",
            new String[] { "en" },
            "Manila",
            "63",
            Currency.Philippine_Peso,
            Continent.Asia),
    Pitcairn(
            "Pitcairn",
            "pn",
            "pcn",
            new String[] {},
            "Adamstown",
            "870",
            Currency.New_Zealand_Dollar,
            Continent.Oceania),
    Poland(
            "Poland",
            "pl",
            "pol",
            new String[] { "pl" },
            "Warsaw",
            "48",
            Currency.Polish_Zloty,
            Continent.Europe),
    Portugal(
            "Portugal",
            "pt",
            "prt",
            new String[] { "pt" },
            "Lisbon",
            "351",
            Currency.Euro,
            Continent.Europe),
    Puerto_Rico(
            "Puerto Rico",
            "pr",
            "pri",
            new String[] { "es" },
            "San Juan",
            "+1-787 and 1-939",
            Currency.US_Dollar,
            Continent.North_America),
    Qatar(
            "Qatar",
            "qa",
            "qat",
            new String[] { "ar" },
            "Doha",
            "974",
            Currency.Qatari_Rial,
            Continent.Asia),
    Republic_of_the_Congo(
            "Republic of the Congo",
            "cg",
            "cog",
            new String[] {},
            "Brazzaville",
            "242",
            Currency.CFA_Franc_BEAC,
            Continent.Africa),
    Reunion(
            "Reunion",
            "re",
            "reu",
            new String[] {},
            "Saint-Denis",
            "262",
            Currency.Euro,
            Continent.Africa),
    Romania(
            "Romania",
            "ro",
            "rou",
            new String[] { "ro" },
            "Bucharest",
            "40",
            Currency.Romanian_New_Leu,
            Continent.Europe),
    Russia(
            "Russia",
            "ru",
            "rus",
            new String[] { "ru" },
            "Moscow",
            "7",
            Currency.Russian_Ruble,
            Continent.Europe),
    Rwanda(
            "Rwanda",
            "rw",
            "rwa",
            new String[] {},
            "Kigali",
            "250",
            Currency.Rwanda_Franc,
            Continent.Africa),
    Saint_Barthelemy(
            "Saint Barthelemy",
            "bl",
            "blm",
            new String[] {},
            "Gustavia",
            "590",
            Currency.Euro,
            Continent.North_America),
    Saint_Helena(
            "Saint Helena",
            "sh",
            "shn",
            new String[] {},
            "Jamestown",
            "290",
            Currency.St_Helena_Pound,
            Continent.Africa),
    Saint_Kitts_and_Nevis(
            "Saint Kitts and Nevis",
            "kn",
            "kna",
            new String[] {},
            "Basseterre",
            "+1-869",
            Currency.East_Caribbean_Dollar,
            Continent.North_America),
    Saint_Lucia(
            "Saint Lucia",
            "lc",
            "lca",
            new String[] {},
            "Castries",
            "+1-758",
            Currency.East_Caribbean_Dollar,
            Continent.North_America),
    Saint_Martin(
            "Saint Martin",
            "mf",
            "maf",
            new String[] {},
            "Marigot",
            "590",
            Currency.Euro,
            Continent.North_America),
    Saint_Pierre_and_Miquelon(
            "Saint Pierre and Miquelon",
            "pm",
            "spm",
            new String[] {},
            "Saint-Pierre",
            "508",
            Currency.Euro,
            Continent.North_America),
    Saint_Vincent_and_the_Grenadines(
            "Saint Vincent and the Grenadines",
            "vc",
            "vct",
            new String[] {},
            "Kingstown",
            "+1-784",
            Currency.East_Caribbean_Dollar,
            Continent.North_America),
    Samoa(
            "Samoa",
            "ws",
            "wsm",
            new String[] {},
            "Apia",
            "685",
            Currency.Samoan_Tala,
            Continent.Oceania),
    San_Marino(
            "San Marino",
            "sm",
            "smr",
            new String[] {},
            "San Marino",
            "378",
            Currency.Euro,
            Continent.Europe),
    Sao_Tome_and_Principe(
            "Sao Tome and Principe",
            "st",
            "stp",
            new String[] {},
            "Sao Tome",
            "239",
            Currency.Dobra,
            Continent.Africa),
    Saudi_Arabia(
            "Saudi Arabia",
            "sa",
            "sau",
            new String[] { "ar" },
            "Riyadh",
            "966",
            Currency.Saudi_Riyal,
            Continent.Asia),
    Senegal(
            "Senegal",
            "sn",
            "sen",
            new String[] {},
            "Dakar",
            "221",
            Currency.CFA_Franc_BCEAO,
            Continent.Africa),
    Serbia(
            "Serbia",
            "rs",
            "srb",
            new String[] { "sr", "sr" },
            "Belgrade",
            "381",
            Currency.Dinar,
            Continent.Europe),
    Seychelles(
            "Seychelles",
            "sc",
            "syc",
            new String[] {},
            "Victoria",
            "248",
            Currency.Seychelles_Rupee,
            Continent.Africa),
    Sierra_Leone(
            "Sierra Leone",
            "sl",
            "sle",
            new String[] {},
            "Freetown",
            "232",
            Currency.Sierra_Leone_Leone,
            Continent.Africa),
    Singapore(
            "Singapore",
            "sg",
            "sgp",
            new String[] { "en", "zh" },
            "Singapur",
            "65",
            Currency.Singapore_Dollar,
            Continent.Asia),
    Sint_Maarten(
            "Sint Maarten",
            "sx",
            "sxm",
            new String[] {},
            "Philipsburg",
            "599",
            Currency.Netherlands_Antillean_Guilder,
            Continent.North_America),
    Slovakia(
            "Slovakia",
            "sk",
            "svk",
            new String[] { "sk" },
            "Bratislava",
            "421",
            Currency.Euro,
            Continent.Europe),
    Slovenia(
            "Slovenia",
            "si",
            "svn",
            new String[] { "sl" },
            "Ljubljana",
            "386",
            Currency.Euro,
            Continent.Europe),
    Solomon_Islands(
            "Solomon Islands",
            "sb",
            "slb",
            new String[] {},
            "Honiara",
            "677",
            Currency.Solomon_Islands_Dollar,
            Continent.Oceania),
    Somalia(
            "Somalia",
            "so",
            "som",
            new String[] {},
            "Mogadishu",
            "252",
            Currency.Somali_Shilling,
            Continent.Africa),
    South_Africa(
            "South Africa",
            "za",
            "zaf",
            new String[] { "en" },
            "Pretoria",
            "27",
            Currency.South_African_Rand,
            Continent.Africa),
    South_Georgia_and_the_South_Sandwich_Islands(
            "South Georgia and the South Sandwich Islands",
            "gs",
            "sgs",
            new String[] {},
            "Grytviken",
            "",
            Currency.Pound_Sterling,
            Continent.Antarctica),
    South_Korea(
            "South Korea",
            "kr",
            "kor",
            new String[] { "ko" },
            "Seoul",
            "82",
            Currency.Korean_Won,
            Continent.Asia),
    South_Sudan(
            "South Sudan",
            "ss",
            "ssd",
            new String[] {},
            "Juba",
            "211",
            Currency.South_Sudan_Pound,
            Continent.Africa),
    Spain(
            "Spain",
            "es",
            "esp",
            new String[] { "ca", "es" },
            "Madrid",
            "34",
            Currency.Euro,
            Continent.Europe),
    Sri_Lanka(
            "Sri Lanka",
            "lk",
            "lka",
            new String[] {},
            "Colombo",
            "94",
            Currency.Sri_Lanka_Rupee,
            Continent.Asia),
    Sudan(
            "Sudan",
            "sd",
            "sdn",
            new String[] { "ar" },
            "Khartoum",
            "249",
            Currency.Sudanese_Pound,
            Continent.Africa),
    Suriname(
            "Suriname",
            "sr",
            "sur",
            new String[] {},
            "Paramaribo",
            "597",
            Currency.Surinam_Dollar,
            Continent.South_America),
    Svalbard_and_Jan_Mayen(
            "Svalbard and Jan Mayen",
            "sj",
            "sjm",
            new String[] {},
            "Longyearbyen",
            "47",
            Currency.Norwegian_Krone,
            Continent.Europe),
    Swaziland(
            "Swaziland",
            "sz",
            "swz",
            new String[] {},
            "Mbabane",
            "268",
            Currency.Swaziland_Lilangeni,
            Continent.Africa),
    Sweden(
            "Sweden",
            "se",
            "swe",
            new String[] { "sv" },
            "Stockholm",
            "46",
            Currency.Swedish_Krona,
            Continent.Europe),
    Switzerland(
            "Switzerland",
            "ch",
            "che",
            new String[] { "fr", "de", "it" },
            "Berne",
            "41",
            Currency.Swiss_Franc,
            Continent.Europe),
    Syria(
            "Syria",
            "sy",
            "syr",
            new String[] { "ar" },
            "Damascus",
            "963",
            Currency.Syrian_Pound,
            Continent.Asia),
    Taiwan(
            "Taiwan",
            "tw",
            "twn",
            new String[] { "zh" },
            "Taipei",
            "886",
            Currency.Taiwan_Dollar,
            Continent.Asia),
    Tajikistan(
            "Tajikistan",
            "tj",
            "tjk",
            new String[] {},
            "Dushanbe",
            "992",
            Currency.Tajik_Somoni,
            Continent.Asia),
    Tanzania(
            "Tanzania",
            "tz",
            "tza",
            new String[] {},
            "Dodoma",
            "255",
            Currency.Tanzanian_Shilling,
            Continent.Africa),
    Thailand(
            "Thailand",
            "th",
            "tha",
            new String[] { "th" },
            "Bangkok",
            "66",
            Currency.Thai_Baht,
            Continent.Asia),
    Togo(
            "Togo",
            "tg",
            "tgo",
            new String[] {},
            "Lome",
            "228",
            Currency.CFA_Franc_BCEAO,
            Continent.Africa),
    Tokelau(
            "Tokelau",
            "tk",
            "tkl",
            new String[] {},
            "",
            "690",
            Currency.New_Zealand_Dollar,
            Continent.Oceania),
    Tonga(
            "Tonga",
            "to",
            "ton",
            new String[] {},
            "Nuku'alofa",
            "676",
            Currency.Tongan_Paanga,
            Continent.Oceania),
    Trinidad_and_Tobago(
            "Trinidad and Tobago",
            "tt",
            "tto",
            new String[] {},
            "Port of Spain",
            "+1-868",
            Currency.Trinidad_and_Tobago_Dollar,
            Continent.North_America),
    Tunisia(
            "Tunisia",
            "tn",
            "tun",
            new String[] { "ar" },
            "Tunis",
            "216",
            Currency.Tunisian_Dollar,
            Continent.Africa),
    Turkey(
            "Turkey",
            "tr",
            "tur",
            new String[] { "tr" },
            "Ankara",
            "90",
            Currency.Turkish_Lira,
            Continent.Asia),
    Turkmenistan(
            "Turkmenistan",
            "tm",
            "tkm",
            new String[] {},
            "Ashgabat",
            "993",
            Currency.Manat,
            Continent.Asia),
    Turks_and_Caicos_Islands(
            "Turks and Caicos Islands",
            "tc",
            "tca",
            new String[] {},
            "Cockburn Town",
            "+1-649",
            Currency.US_Dollar,
            Continent.North_America),
    Tuvalu(
            "Tuvalu",
            "tv",
            "tuv",
            new String[] {},
            "Funafuti",
            "688",
            Currency.Australian_Dollar,
            Continent.Oceania),
    Uganda(
            "Uganda",
            "ug",
            "uga",
            new String[] {},
            "Kampala",
            "256",
            Currency.Uganda_Shilling,
            Continent.Africa),
    Ukraine(
            "Ukraine",
            "ua",
            "ukr",
            new String[] { "uk" },
            "Kiev",
            "380",
            Currency.Ukraine_Hryvnia,
            Continent.Europe),
    United_Arab_Emirates(
            "United Arab Emirates",
            "ae",
            "are",
            new String[] { "ar" },
            "Abu Dhabi",
            "971",
            Currency.Arab_Emirates_Dirham,
            Continent.Asia),
    United_Kingdom(
            "United Kingdom",
            "gb",
            "gbr",
            new String[] { "en" },
            "London",
            "44",
            Currency.Pound_Sterling,
            Continent.Europe),
    United_States(
            "United States",
            "us",
            "usa",
            new String[] { "en", "es" },
            "Washington",
            "1",
            Currency.US_Dollar,
            Continent.North_America),
    United_States_Minor_Outlying_Islands(
            "United States Minor Outlying Islands",
            "um",
            "umi",
            new String[] {},
            "-",
            "1",
            Currency.US_Dollar,
            Continent.Oceania),
    Uruguay(
            "Uruguay",
            "uy",
            "ury",
            new String[] { "es" },
            "Montevideo",
            "598",
            Currency.Uruguayan_Peso,
            Continent.South_America),
    US_Virgin_Islands(
            "U.S. Virgin Islands",
            "vi",
            "vir",
            new String[] {},
            "Charlotte Amalie",
            "+1-340",
            Currency.US_Dollar,
            Continent.North_America),
    Uzbekistan(
            "Uzbekistan",
            "uz",
            "uzb",
            new String[] {},
            "Tashkent",
            "998",
            Currency.Uzbekistan_Sum,
            Continent.Asia),
    Vanuatu(
            "Vanuatu",
            "vu",
            "vut",
            new String[] {},
            "Port Vila",
            "678",
            Currency.Vanuatu_Vatu,
            Continent.Oceania),
    Vatican(
            "Vatican",
            "va",
            "vat",
            new String[] {},
            "Vatican City",
            "379",
            Currency.Euro,
            Continent.Europe),
    Venezuela(
            "Venezuela",
            "ve",
            "ven",
            new String[] { "es" },
            "Caracas",
            "58",
            Currency.Venezuelan_Bolivar,
            Continent.South_America),
    Vietnam(
            "Vietnam",
            "vn",
            "vnm",
            new String[] { "vi" },
            "Hanoi",
            "84",
            Currency.Vietnamese_Dong,
            Continent.Asia),
    Wallis_and_Futuna(
            "Wallis and Futuna",
            "wf",
            "wlf",
            new String[] {},
            "Mata Utu",
            "681",
            Currency.CFP_Franc,
            Continent.Oceania),
    Western_Sahara(
            "Western Sahara",
            "eh",
            "esh",
            new String[] {},
            "El-Aaiun",
            "212",
            Currency.Moroccan_Dirham,
            Continent.Africa),
    Yemen(
            "Yemen",
            "ye",
            "yem",
            new String[] { "ar" },
            "Sanaa",
            "967",
            Currency.Yemeni_Rial,
            Continent.Asia),
    Zambia(
            "Zambia",
            "zm",
            "zmb",
            new String[] {},
            "Lusaka",
            "260",
            Currency.Zambian_Kwacha,
            Continent.Africa),
    Zimbabwe(
            "Zimbabwe",
            "zw",
            "zwe",
            new String[] {},
            "Harare",
            "263",
            Currency.Zimbabwe_Dollar,
            Continent.Africa);
            
    public final String    capital;
    /**
     * ISO-2 Code
     */
    public final String    code;
                           
    /**
     * ISO-3 Code
     */
    public final String    codeIso3;
    public final String[]  langs;
    public final Continent continent;
    public final Currency  currency;
    public final String    name;
    public final String    phone;
                           
    private final String   i18nCode;
                           
    private Country2(String n, String iso2, String iso3, String[] langs, String cap, String p, Currency curr, Continent c) {
        name = n;
        code = iso2;
        codeIso3 = iso3;
        this.langs = langs;
        continent = c;
        phone = p;
        currency = curr;
        capital = cap;
        i18nCode = "country." + code;
    }
    
    @Override
    public String key() {
        return i18nCode;
    }
    
    private static Map<String, Country2> _cache = new HashMap<String, Country2>();
    
    public static Country2 getByISO2Code(String code) {
        
        String lowerCase = code.toLowerCase();
        Country2 c = _cache.get(lowerCase);
        
        if (c == null) {
            c = getByISOCode(lowerCase);
            if (c == null) throw new IllegalArgumentException("unknown country code: " + code);
            _cache.put(lowerCase, c);
        }
        
        return c;
    }
    
    static Country2 getByISOCode(String code) {
        for (Country2 c : Country2.values()) {
            if (c.code.equalsIgnoreCase(code)) {
                return c;
            }
        }
        return null;
    }
    
    public static void main(String[] args) {
    
//        String templ = "%s(\"%s\", \"%s\", \"%s\", new String[]{%s}, \"%s\", \"%s\", Currency.%s, Continent.%s),";
//        
//        for (Country country : Country.values()) {
//            List<Locale> langs = LocaleUtils.languagesByCountry(country.code.toUpperCase());
//            StringBuilder languages = new StringBuilder();
//            
//            for (int i = 0; i < langs.size(); i++) {
//                if (i > 0) {
//                    languages.append(",");
//                }
//                languages.append("\"").append(langs.get(i).getLanguage().toLowerCase()).append("\"");
//            }
//            
//            String name2 = country.name.replaceAll(" ", "_").replaceAll("-", "").replaceAll("\\.", "");
//            
//            String format = String.format(templ, name2, country.name, country.code, country.codeIso3, languages, country.capital, country.phone, country.currency, country.continent);
//            System.out.println(format);
//            
//        }
    
    }
    
}
